library(integIRTy)
library(doParallel)
registerDoParallel(makeCluster(3, type = "SOCK"))
# getDoParWorkers()
data(OV)
ll <- list(CN_N, Expr_N, Methy_N)
pp <- list(CN_T, Expr_T, Methy_T)
#whatmore <- intIRTeasyRunFromRaw(pp, ll, assayType=c("CN", "Expr", "Methy"), permutationMethod="gene sampling")
#whatmore2 <- intIRTeasyRunFromRaw(pp, ll, assayType=c("CN", "Expr", "Methy"), permutationMethod="sample label permutation", parallel=TRUE)
