library(integIRTy)
library(OvarianData)
data(OV)
ll <- list(CN_N, Expr_N, Methy_N)
pp <- list(CN_T, Expr_T, Methy_T)
#whatever <- intIRTeasyRunFromRaw(pp, ll, assayType=c("CN", "Expr", "Methy"))
